<Pythonlab>
  <config><![CDATA[{
  "game_id": 72,
  "created_at": "2025-01-24T21:49:29.000Z",
  "level_num": "custom",
  "user_id": 18602,
  "properties": {
    "encrypted": "false",
    "ai_tutor_available": "false",
    "submittable": "false",
    "hide_share_and_remix": "false",
    "predict_settings": {
      "isPredictLevel": false
    },
    "start_sources": {
      "files": {
        "0": {
          "id": "0",
          "name": "main.py",
          "language": "py",
          "contents": "dog_name = \"Stringer Bell\"\nhuman_years = 5\n\nprint(\"The dog named \" + dog_name + \" is \" + human_years + \" human years old.\")\n# print(\"The dog named \" + dog_name + \" is \" + str(human_years) + \" human years old.\")",
          "folderId": "0",
          "active": true,
          "open": true
        }
      },
      "folders": {
      }
    },
    "long_instructions": "# Numeric Variables\r\n\r\n::: details [**✅ Step 1**]\r\nRun the program and observe the results. \r\n:::\r\n\r\n::: details [**✅ Step 2**]\r\nComment out the `print()` statement that results in the error and uncomment the `print()` statement below it.\r\n:::\r\n\r\n::: details [**✅ Step 3**]\r\nDiscuss with your partner why the error might have happened.\r\n:::\r\n",
    "name_suffix": "_beta"
  },
  "published": true,
  "audit_log": "[{\"changed_at\":\"2025-01-24T21:49:29.946+00:00\",\"changed\":[\"cloned from \\\"datascience-U2L2-L4-6templ_2024-pilot\\\"\"],\"cloned_from\":\"datascience-U2L2-L4-6templ_2024-pilot\"}]"
}]]></config>
</Pythonlab>
